### PR TITLE
SD-794 Add GDPR checkboxes to donation form

### PR DESCRIPTION
**Pull request by eronisko**
image

### CODE REVIEW

**Comment by eronisko** [comment]
@jsuchal moze byt takto?

**Comment by jsuchal** [comment]
Spojme to do jedneho checkboxu a dajme to ako tri odstavce.

**Comment by eronisko** [comment]
image

**Comment by eronisko** [comment]
@jsuchal 
image

**Comment by jsuchal** [comment]
Fajne.

**Pull request merged**
